comment_width               = 100
format_code_in_doc_comments = true
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = true
imports_layout              = "Vertical"
merge_imports               = true
unstable_features           = true
wrap_comments               = true
