[package]
authors    = ["Philippe Lafontaine <lafontaine.philippe@gmail.com>"]
edition    = "2018"
license    = "MIT"
name       = "viewbuilder-core"
repository = "https://github.com/BleuShan/viewbuilder-rs.git"
version    = "0.1.0"

[dependencies]
derive_more = "0.99.9"
