[package]
authors    = ["Philippe Lafontaine <lafontaine.philippe@gmail.com>"]
edition    = "2018"
license    = "MIT"
name       = "viewbuilder-core"
readme     = "../README.md"
repository = "https://github.com/BleuShan/viewbuilder-rs"
version    = "0.1.0"

[dependencies]
